version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase-if-necessary

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
