name: ubuntu

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    name: Ruby ${{ matrix.ruby.name }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        ruby:
          - { name: 3.1, value: 3.1.7 }
          - { name: 3.2, value: 3.2.8 }
          - { name: 3.3, value: 3.3.7 }

    env:
      BUNDLE_PATH: .bundle

    steps:
      - uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}

      - name: Install dependencies
        run: |
          bundle install

      - name: Run tests
        run: RUBYOPT="-E UTF-8" bundle exec rake
